version: '3'
services:
  web:
    image: "tonyzhang1002/fyp-survey:web"
    ports:
      - "8081:8080"
    networks:
      - survey
  db:
    image: "mongo:latest"
    networks:
      - survey
networks:
  survey:
    driver: bridge